#!/usr/bin/env bash
# start_chroot_script
# Setup for pib.rocks backend and frontend
# Written by Michael Schaar
# GPL V3
########


# Enable debug output and exit on any error
set -x
set -e

# Source common functions and variables, and set up a cleanup trap
source /common.sh
install_cleanup_trap

# Unpack filesystem components to their respective directories with appropriate ownership
unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

ls /home/"${BASE_USER}"/pibrocks/

# Update the package list
apt-get update

# Install required packages for the pib backend
check_install_pkgs ${PIBBACKEND_PKGS}
cgroupfs-umount
cgroupfs-mount

# Remove unnecessary game and office packages to streamline the environment
apt-get remove --yes "aisleriot" "gnome-sudoku" "ace-of-penguins" "gbrainy" "gnome-mines" "gnome-mahjongg" "libreoffice*" "thunderbird*"

# Change to the base user's home directory
cd /home/"${BASE_USER}"
# Download the setup script for the pib backend
wget https://raw.githubusercontent.com/pib-rocks/pib-backend/main/setup/setup-pib.sh
# Change ownership of the setup script to the base user
chown "${BASE_USER}": setup-pib.sh
# Execute the setup script with debug output enabled, ignoring errors in QEMU changeroot
su --login --command "bash -x setup-pib.sh" "${BASE_USER}" || true
custompios_export setup-pib.log.first /home/${BASE_USER}/setup-pib.log

# Start docker manually https://linuxconfig.org/start-docker-daemon-on-linux
# Start the Docker daemon manually in the background without iptables and bridge network support
dockerd --iptables=false --bridge=none &
# Wait for 10 seconds to ensure Docker is fully up and running
sleep 10
cd pibrocks
for i in $(ls *.tar.gz)
do
    docker load < ${i}
    rm ${i}
done

kill $(pgrep -f "dockerd --iptables=false --bridge=none")

if [ -f /etc/sudoers.d/${BASE_USER} ]
then
    rm /etc/sudoers.d/${BASE_USER}
fi

# Unpack the root filesystem at the end to ensure all modifications are applied
unpack /filesystem/root /

# Enable the doitpi_firstboot service to run at startup
systemctl enable doitpi_firstboot.service
# Remove the setup log file if it exists.
#if [ -f /home/${BASE_USER}/setup-pib.log ]
#then
#    rm /home/${BASE_USER}/setup-pib.log
#fi